/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2020-02-15 11:29:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/css/style.css", Long.valueOf(1580710524814L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write(" ");
      out.write("body{\r\n");
      out.write("\tfont-family: arial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#most_outer\r\n");
      out.write("{\r\n");
      out.write(" width:100%;\r\n");
      out.write(" height:auto;\r\n");
      out.write(" background-color: black;\r\n");
      out.write(" color:white;\r\n");
      out.write(" border:solid 1px red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ticket_text\r\n");
      out.write("{\r\n");
      out.write("\tfont-size:40px;\r\n");
      out.write("\tborder:solid 0px white;  \r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-top:30px;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#expandheight\r\n");
      out.write("{\r\n");
      out.write("\theight:30px;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_most_outer\r\n");
      out.write("{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:500px;  \r\n");
      out.write("\tbackground-color:#131313;\r\n");
      out.write("\tpadding-top:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#middle_outer\r\n");
      out.write("{\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tborder:solid 1px black; \r\n");
      out.write("\tbackground-color:grey;   \r\n");
      out.write("\tborder-radius:50px;  \r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#select_outer\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#submitbutton\r\n");
      out.write("{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("\tbackground-color:black;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\tborder-radius: 50px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t   $(document).ready(function(){\r\n");
      out.write("\t\t $(\"#select_outer\").change(function(){\r\n");
      out.write("\t\t\t var ticketchange = $(\"#select_outer\").val();\r\n");
      out.write("\t\t\t console.log(\"ticketerror : \"+ticketchange);\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#submitbutton\").click(function(){\r\n");
      out.write("\t\t\t\talert(\"hello\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'displayresult',\r\n");
      out.write("\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tticketoption : $(\"#select_outer\").val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(responseText) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"return value : \"+responseText);\r\n");
      out.write("\t\t\t\t\t\t//$('#ajaxGetUserServletResponse').text(responseText);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\terror: function(err){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"##########################\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t   });\r\n");
      out.write("\t   });\r\n");
      out.write("\t </script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"most_outer\">\r\n");
      out.write(" <div id=\"ticket_text\">Ticket Tracker</div>\r\n");
      out.write(" <div id=\"expandheight\"></div>\r\n");
      out.write(" \r\n");
      out.write(" <div id=\"center_most_outer\">\r\n");
      out.write(" <div id=\"middle_outer\">\r\n");
      out.write("  <div style=\"border:solid 0px white;margin-top:50px;padding-left:10px;font-size:30px;letter-spacing: 2px;\">Select the Option !</div>             \r\n");
      out.write("  <form action=\"displayresult\" method=\"post\">\r\n");
      out.write("\t <select id=\"select_outer\" name=\"ticketoption\">\r\n");
      out.write("\t  <option value=\"alltickets\">Display All Tickets</option>\r\n");
      out.write("\t  <option value=\"desireticket\">Desire ticket</option>\t\r\n");
      out.write("\t  <option value=\"otherwork\">Other Work</option>\t\r\n");
      out.write("\t  <option value=\"weeklystatus\">Weekly Status</option>\r\n");
      out.write("\t  <option value=\"monthlystatus\">Monthly Status</option>\r\n");
      out.write("\t </select> \r\n");
      out.write("\t <br>  \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t <input type=\"submit\" value=\"Submit\" id=\"submitbutton\">\r\n");
      out.write(" </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
